### ISSUE TITLE
BOM Mouser part incorrect

### ISSUE THREAD

**Issue by ghost** [jakplugg/T_u#4]
The current BOM shows "579-MCP6004T-I/SL" for the 2x op-amps needed, that's the part number for the SOIC-14 version, while the board needs the SOIC-8 package "579-MCP6002T-I/SN"

**Comment by jakplugg** [comment]
Sorry, i only own the google sheets BOM, not any of the mouser ones,
it seems to be already correct?

**Comment by ghost** [comment]
That is from the google sheets BOM, that mouser part listed in the google sheets bom:  "579-MCP6004T-I/SL" (SOIC-14, 7 pin) I believe should be "579-MCP6002T-I/SN" (SOIC-8, 4 pin)

**Comment by grantHarris** [comment]
Ugh. This burned me. Ended up ordering the MCP6004T part without noticing.

**Comment by jakplugg** [comment]
I checked the BOM sheet and the link on the repo and they both seem
right, is there an old BOM floating about? maybe it should be deleted.

**Comment by grantHarris** [comment]
https://docs.google.com/spreadsheets/d/1YzoKF_4KADmYcHr4SySU5rFkUqZim7LaVXBFByAKBcs/edit#gid=1626775796

![image](https://user-images.githubusercontent.com/1750776/77571400-90141980-6e8a-11ea-9d54-d0ba0e5f4945.png)

**Comment by jakplugg** [comment]
Sorry It was me looking at the wrong one, fixed!
