### ISSUE TITLE
Missing drill file?

### ISSUE THREAD

**Issue by terje** [jakplugg/T_u#5]
Heya,

Thanks for your effort on this! It's great to have Temps Utile available in 8HP :)

I think the circuit board gerber file is missing the drill file, however. Could you add it in?

Thanks!

Kindly, Terje

**Comment by jakplugg** [comment]
the "NC" file is the drill file, you could rename the file extension to "DRL"

**Comment by terje** [comment]
Thanks so much, I didn't know that!
